# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# HAVE_WORDS_BIGENDIAN_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_WORDS_BIGENDIAN_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The HAVE_WORDS_BIGENDIAN_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/join/Desktop/vlc3.0/vlc/contrib/win32/soxr/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/join/Desktop/vlc3.0/vlc/contrib/win32/soxr/CMakeFiles/cmTC_cfe6c-HAVE_WORDS_BIGENDIAN_EXITCODE.exe
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.5/Modules/CheckCSourceRuns.cmake
#                 [2]	/home/join/Desktop/vlc3.0/vlc/contrib/win32/soxr/cmake/Modules/TestBigEndian.cmake
#                 [1]	/home/join/Desktop/vlc3.0/vlc/contrib/win32/soxr/CMakeLists.txt

set( HAVE_WORDS_BIGENDIAN_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

